### ISSUE TITLE
There's no validity check on adding single-item metadata

### ISSUE THREAD

**Issue by patrickmj** [NEU-Libraries/drs-toolkit-wp-plugin#144]
Any input for a new metadata field in the single item settings seems to be accepted.

![validitynoncheck](https://user-images.githubusercontent.com/153262/49773655-f2f69700-fcbf-11e8-8aca-0765232a3021.png)

**Comment by sarahjeansweeney** [comment]
I think this might be intended. The MODS note field includes an uncontrolled display label attribute. IIRC, MODS display shares the display label through the API, not the actual element (so "nope" instead of "mods:note"). Rather than anticipating all possible display labels and making them available in the Single Item Page Settings, site editors can manually enter in the display labels for the notes in their metadata. You can see an example of this in the ECDA items: https://repository.library.northeastern.edu/files/neu:m0415d93h
That record contains three custom note fields with display labels: Citation, Acquisitions Source, and Learn more. Only Citation and Acquisition Source are turned on in their CERES site.

**Comment by patrickmj** [comment]
OK then! Thanks! Always happy to close an issue without writing code!
