### ISSUE TITLE
When on pagination > 1, faceting returns zero results even when results exist

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#72]
How to reproduce:

 * http://latinamericanartists.northeastern.edu/browse
 * Click on page 2
 * Then click on the facet `Type -> Text`
 * It will report no results found 

Refresh page, and click on facet `Type -> Test` -- results will be shown.

**Comment by elizoller** [comment]
Ah. Forgot to reset pagination on clicking a facet so when you go to the last page and then click a facet, the page you are trying to go to is greater than the number of pages that exist because the result set has been decreased below the threshold for creating the last page. Will push a fix up shortly.
